import { CLIENT_EVENTS } from "../consts/ClientEvents";

export type ClientSocketEvents = {
  // Lobby
  [CLIENT_EVENTS.LOBBY_CREATE]: undefined;
  [CLIENT_EVENTS.LOBBY_JOIN]: { lobbyIdJoin: string };
  [CLIENT_EVENTS.LOBBY_START_GAME]: undefined;
  [CLIENT_EVENTS.LOBBY_LEAVE]: undefined;
  [CLIENT_EVENTS.LOBBY_DELETE]: undefined;

  // Game
  [CLIENT_EVENTS.GAME_READY]: undefined;
  [CLIENT_EVENTS.GAME_PLAY_SECRET_OPERATOR]: undefined;
  [CLIENT_EVENTS.GAME_PLAY_SECURITY_AGENT]: undefined;
  [CLIENT_EVENTS.GAME_PLAY_INFORMANT]: undefined;
  [CLIENT_EVENTS.GAME_PLAY_MAGNATE]: undefined;
  [CLIENT_EVENTS.GAME_PLAY_DISCREET_ASSISTANT]: undefined;
  [CLIENT_EVENTS.GAME_PLAY_UNDERCOVER_AGENT]: undefined;
  [CLIENT_EVENTS.GAME_PLAY_STRATEGIST]: undefined;
  [CLIENT_EVENTS.GAME_PLAY_DIRECTOR_OF_OPERATIONS]: undefined;
  [CLIENT_EVENTS.GAME_PLAY_DIPLOMAT]: undefined;
  [CLIENT_EVENTS.GAME_PLAY_DOUBLE_AGENT]: undefined;
};
